name: Build a Pelican Website
on:
  push:
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apache/infrastructure-actions/pelican@main
        with:
          destination: 'asf-site-work2'
          gfm: 'true'
          version: '4.8.0'
      - name: test
        run: |
          pelican --version
          ls -la
          ls -lR theme
          git status
        if: always()
