name: Build a Pelican Website
on:
  push:
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sebbASF/infra-actions/pelican@main
        with:
          destination: 'asf-site-work2'
          gfm: 'true'
          version: '4.5.4'
      - name: test
        run: |
          python3 -V
          pip list
          pelican --version
        if: always()
