name: Build a Pelican Website
on:
  push:
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sebbASF/infra-actions/pelican@action-test
      # - uses: apache/infrastructure-actions/pelican@action-data
        with:
          destination: 'asf-site-work2'
          gfm: 'true'
